Adding deaggregation logic
lifion/lifion-kinesis pull request #388
Opened 2020-12-04 16:34 UTC by BizzlePop34

2020-12-10 16:36 UTC, jennyEckstein reviewed
Looks very nice, I found some minor changes

2020-12-10 16:36 UTC, jennyEckstein commented on lib/polling-consumer.js
> +    const records = await Promise.all(deaggCollection.map(recordsDecoder));
Don't see a limit for Promise.all, maybe use p-map?

2020-12-10 16:36 UTC, jennyEckstein commented on lib/deaggregate.js
> +const MAGIC_NUMBER = 'f3899ac2';
I checked the documentation, and absolutely hate that they call it MAGIC_NUMBER. Can we rename the variable KPL_MAGIC_NUMBER, so its more clear where it comes from.

2020-12-10 16:36 UTC, jennyEckstein commented on lib/deaggregate.js
> +  // first 4 bytes are the kpl assigned magic number
instead of kpl can spell out Kinesis Producer Library (KPL)

2020-12-10 16:36 UTC, jennyEckstein commented on lib/deaggregate.js
> +      });
Let destructure kinesisRecord, so we can clean up this object a little.

2020-12-10 16:36 UTC, jennyEckstein commented on lib/deaggregate.js
> +    });
destructure kinesisRecord would make it a bit cleaner.

2020-12-10 16:36 UTC, jennyEckstein commented on lib/deaggregate.js
> +
let remove this empty line

2020-12-10 16:36 UTC, jennyEckstein commented on lib/deaggregate.test.js
> +      Data: Buffer.concat([Buffer.from('f3899ac2', 'hex'), buff, checksum]),
let put 'f3899ac2' in a constant

2020-12-10 16:36 UTC, jennyEckstein commented on lib/deaggregate.test.js
> +    const deaggRecord = {
Since this object is only used once, we can place it directly in deaggregate function

2020-12-18 20:02 UTC, eaviles requested changes
@BizzlePop34 changes look OK but let's make de-aggregation optional just like in the KPL/KCL. Can you please add a "useDeaggregation" (or something similar) to the public constructor?

2021-03-22 18:51 UTC, merged